---
name: docs

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master
    paths:
      - '**.md'
  schedule:
    - cron: '4 5 * * 6'

permissions:
  contents: read

jobs:
  remark-lint:
    name: remark-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run remark-lint
        uses: rickstaa/action-remark-lint@v1
  lychee:
    name: lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Define lychee path
        uses: haya14busa/action-cond@v1
        id: condition
        with:
          cond: ${{ github.event_name == 'schedule' }}
          if_true: './**/*.md'
          if_false: 'README.md'
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          args: >-
            -v -m 1 --require-https
            --exclude 'https://(github.com/SpiderX|www.codacy.com)/*'
            -n ${{ steps.condition.outputs.value }}
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
